jobs:
  n:
    cmd: "/usr/bin/sleep 10"
    numprocs: 1
    umask: 022
    workingdir: /tmp
    autostart: true
    autorestart: true
    exitcodes:
      - 0
      - 2
    startretries: 3
    AAAAAA: "SIEP"
    starttime: 1
    stopsignal: QUIT
    stoptime: 10
    stdout: /tmp/nginx.stdout
    stderr: /tmp/nginx.stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42

  ls:
    cmd: "/usr/bin/ls"
    numprocs: 1
    umask: 077
    workingdir: /home/jmeruma/Downloads
    autostart: false
    autorestart: true
    exitcodes: 0
    startretries: 3
    starttime: 5
    stopsignal: QUIT
    stoptime: 10
    stdout: ~/Desktop/ls.out
    stderr: ~/Desktop/ls.err

  cheese:
    cmd: "/usr/bin/sleep 10"
    numprocs: 1
    umask: 077
    workingdir: /tmp
    autostart: true
    autorestart: true
    exitcodes: 0
    startretries: 3
    starttime: 5
    stopsignal: QUIT
    stoptime: 10
    stdout: /tmp/vgsworker.stdout
    stderr: /tmp/vgsworker.stderr